### PR TITLE
the elasticsearch library renamed (?) bulk_index

### PR DESCRIPTION
**Pull request by einvalentin**
The new api is called bulk() but seems to accept the same parameters :-)

__Steps to reproduce:__

Environment Setup:

        * git clone https://github.com/Sparrho/bungiesearch.git
        * mkvirtualenv bungiesearch
        * cd tests
        * pip install -r requirements.txt (Installs elasticsearch 2.1.0)

```
* (bungiesearch)erebus:tests valentin$ python manage.py  test

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/valentin/Projects/bungiesearch/tests/core/models.py", line 5, in <module>
    class Article(models.Model):
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/db/models/base.py", line 189, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/valentin/.virtualenvs/bungiesearch/lib/python2.7/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/valentin/Projects/bungiesearch/bungiesearch/managers.py", line 36, in contribute_to_class
    from .signals import get_signal_processor
  File "/Users/valentin/Projects/bungiesearch/bungiesearch/signals.py", line 7, in <module>
    from .utils import update_index, delete_index_item
  File "/Users/valentin/Projects/bungiesearch/bungiesearch/utils.py", line 6, in <module>
    from elasticsearch.helpers import bulk_index
ImportError: cannot import name bulk_index
```

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
Okay, merged, sorry for the delay!

**Comment by NullSoldier** [comment]
Any idea when this will be released?

**Comment by ChristopherRabotin** [comment]
Yes, I'll make sure to do that in the next eighteen hours, I'll have time.

Best regards,
Christopher Rabotin.

**Comment by NullSoldier** [comment]
I realize my reply sounded aggressive but I want to say thank you more than anything. I think BungieSearch is a great effort!

**Comment by ChristopherRabotin** [comment]
No worries at all, I didn't find it aggressive 😉

Best regards,
Christopher Rabotin.

**Comment by ChristopherRabotin** [comment]
@NullSoldier , version 1.2.2 has been released on pypi.

**Pull request merged**
